// react/src/app/app.js

import React from 'react';
import { Link, NavLink } from "react-router-dom";

import AppRouting from './app-routing';
import ganatanLogo from '../assets/params/images/logo/ganatan-logo.png';

import './app.css';

import 'bootstrap/dist/js/bootstrap.bundle.min.js'

class App extends React.Component {

  constructor(props) {
    super(props);
    this.title = 'react-bootstrap';
    this.footerUrl = 'https://www.ganatan.com';
    this.footerLink = 'www.ganatan.com';
  }

  componentDidMount() {
    const navMain = document.getElementById('navbarCollapse');
    if (navMain) {
      navMain.onclick = function onClick() {
        if (navMain) {
          navMain.classList.remove("show");
        }
      }
    }
  }

  render() {
    const style = {
      backgroundColor: 'black',
    };

    return (
      <div >
        <header className="navbar navbar-expand-md navbar-dark fixed-top nga-navbar">
          <nav className="container" aria-label="Main navigation">
            <NavLink className="navbar-brand" to="/">
              <img src={ganatanLogo} width="25" height="25" alt="Ganatan Logo" />
              <span className="nga-logo mx-1">ganatan</span>
            </NavLink>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarCollapse">
              <ul className="navbar-nav mx-auto">
                <li className="nav-item">
                  <NavLink className="nav-link" to="/"><i className="fas fa-home me-1"></i>Home</NavLink>
                </li>
              </ul>
              <ul className="navbar-nav me-auto">
                <li className="nav-item">
                  <NavLink className="nav-link" to="/about"><i className="far fa-question-circle me-1"></i>About</NavLink>
                </li>
                <li className="nav-item">
                  <NavLink className="nav-link" to="/contact"><i className="fas fa-envelope me-1"></i>Contact</NavLink>
                </li>
              </ul>

              <form className="d-flex">
                <Link to="/signup">
                  <button type="button" className="btn btn-sm btn-primary me-2"><i className="fas fa-user-plus me-2"></i>Sign
                    up</button>
                </Link>
                <Link to="/login">
                  <button type="button" className="btn btn-sm btn-outline-light me-2"><i
                    className="fas fa-sign-in-alt me-2"></i>Login</button>
                </Link>
              </form>

            </div>
          </nav>
        </header>
        <main>
          <AppRouting />
        </main>
        <footer className="nga-footer">
          <div className="py-3 text-center" style={style}>
            <div className="container">
              <a href="{ this.footerUrl }">{this.footerLink}</a>
            </div>
          </div>
        </footer>
      </div >

    )
  }

}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-starter';
  version = 'Angular version 11.2.7';
}

<header>
  <nav class="navbar navbar-expand-md fixed-top navbar-dark " style="background-color: #212121;">
    <a class="navbar-brand" routerLink="/">
      <span style="color:white">ganatan</span>
      <img src="./assets/params/images/logo/ganatan.png" width="20" height="20" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" routerLink="/">
            <i class="fas fa-home mr-1"></i> Home
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" routerLink="/about">
            <i class="far fa-question-circle mr-1"></i> About
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" routerLink="/contact">
            <i class="fas fa-envelope mr-1"></i> Contact
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<main>
  <div class="container-fluid">
    <div class="row pt-1 mb-2">
      <div class="col-md-4 text-center mb-2">
        <h3 class="h5">
          <i class="fab fa-android fa-lg mr-2 text-primary"></i>
          {{ title }}<i class="fab fa-apple fa-lg ml-2 mr-1 text-primary"></i>
        </h3>
      </div>
      <div class="col-md-4 text-center">
        <h3 class="h5">{{angular}}&nbsp;&nbsp;<img src="./assets/params/images/logo/angular.png" width="36" height="36"
            alt=""></h3>
      </div>
      <div class="col-md-4 text-center">
        <h3 class="h5">{{bootstrap}}&nbsp;&nbsp;<img src="./assets/params/images/logo/bootstrap.png" width="28"
            height="28" alt=""></h3>
      </div>
    </div>
    <hr>
    <div class="row mb-1">
      <div class="col-md-12 text-center">
        <h3 class="h6">Features&nbsp;&nbsp;<i class="fas fa-list"></i></h3>
      </div>
    </div>
    <div class="row mb-1">
      <div class="col-md-12 text-center">
        <router-outlet></router-outlet>
      </div>
    </div>
  </div>
</main>
