// src/app/modules/general/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  name = environment.application.name;
  angular = environment.application.angular;
  bootstrap = environment.application.bootstrap;
  fontawesome = environment.application.fontawesome;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="row pt-1 mb-2">
    <div class="col-md-3 text-center mb-2">
      <h1 class="h5">
        <i class="fas fa-laptop fa-lg mr-2 text-primary"></i>
        {{ name }}
        <i class="fas fa-mobile-alt fa-lg ml-2 mr-1 text-primary"></i>
        <i class="fas fa-tablet-alt fa-lg ml-2 mr-1 text-primary"></i>
      </h1>
    </div>
    <div class="col-md-3 text-center text-danger">
      <h2 class="h5">
        {{ angular }}<i class="fab fa-angular fa-lg ml-2 mr-1 text-danger"></i>
      </h2>
    </div>
    <div class="col-md-3 text-center text-primary">
      <h2 class="h5">
        {{ bootstrap }}<i class="fab fa-bootstrap fa-lg ml-2 mr-1 text-primary"></i>
      </h2>
    </div>
    <div class="col-md-3 text-center text-warning">
      <h2 class="h5">
        {{ fontawesome }}<i class="fab fa-font-awesome-flag fa-lg ml-2 mr-1 text-warning"></i>
      </h2>
    </div>
  </div>
  <hr>
  <div class="row mb-1">
    <div class="col-md-12 text-center">
      <h3 class="h6">Features&nbsp;&nbsp;<i class="fas fa-list"></i></h3>
    </div>
  </div>
  
  <div class="row pt-2">
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
      <div class="card bg-light mb-3">
        <a routerLink="/bootstrap-prototype">
          <div class="card-header">
            <div class="row">
              <div class="col-10 col-xl-10">
                <h5 class="card-title">Bootstrap Prototype</h5>
              </div>
              <div class="col-2 col-xl-2">
                <i class="fab fa-bootstrap fa-lg text-primary"></i>
              </div>
            </div>
          </div>
          <div class="card-body">
            <p class="card-text">Bootstrap Prototype Description</p>
          </div>
        </a>
      </div>
    </div>      
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
      <div class="card bg-light mb-3">
        <div class="card-header">
          <div class="row">
            <div class="col-10 col-xl-10">
              <h5 class="card-title">Components</h5>
            </div>
            <div class="col-2 col-xl-2">
              <i class="fas fa-share-alt-square fa-lg text-primary"></i>
            </div>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Components Description</p>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
      <div class="card bg-light mb-3">
        <div class="card-header">
          <div class="row">
            <div class="col-10 col-xl-10">
              <h5 class="card-title">Services</h5>
            </div>
            <div class="col-2 col-xl-2">
              <i class="far fa-address-card fa-lg text-primary"></i>
            </div>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Services Description</p>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
      <div class="card bg-light mb-3">
        <div class="card-header">
          <div class="row">
            <div class="col-10 col-xl-10">
              <h5 class="card-title">Reactive Form</h5>
            </div>
            <div class="col-2 col-xl-2">
              <i class="far fa-address-card fa-lg text-primary"></i>
            </div>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Reactive Form Description</p>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
      <div class="card bg-light mb-3">
        <div class="card-header">
          <div class="row">
            <div class="col-10 col-xl-10">
              <h5 class="card-title">Template Driven Forms</h5>
            </div>
            <div class="col-2 col-xl-2">
              <i class="far fa-address-card fa-lg text-primary"></i>
            </div>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Template Driven Forms Description</p>
        </div>
      </div>
    </div>
  </div>

// frontend-react/src/app/modules/general/home/home.js
import React from 'react';
import { Link } from "react-router-dom";

import './home.css';
import { environment } from '../../../../environments/environment';

class Home extends React.Component {

  constructor(props) {
    super(props);
    this.title = environment.application.name;
    this.version = environment.application.version;
    this.name = environment.application.name;
    this.angular = environment.application.angular;
    this.bootstrap = environment.application.bootstrap;
    this.fontawesome = environment.application.fontawesome;

  }


  

  render() {

    return (
      <div className="container py-5">
        <div className="row">
          <div className="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 text-center mb-2">
            <h1 className="h5">
              <i className="fas fa-laptop fa-lg me-2 text-primary"></i>
              {this.name}
              <i className="fas fa-mobile-alt fa-lg ms-2 text-primary"></i>
            </h1>
          </div>
          <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-3 text-center text-dark mb-2">
            <h2 className="h5">
              {this.version}<i className="fab fa-react fa-lg ms-2"></i>
            </h2>
          </div>
          <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-3 text-center text-primary mb-2">
            <h2 className="h5">
              {this.bootstrap}<i className="fab fa-bootstrap fa-lg ms-2"></i>
            </h2>
          </div>
          <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-3 text-center text-success mb-2">
            <h2 className="h5">
              {this.fontawesome}<i className="fab fa-font-awesome-flag fa-lg ms-2"></i>
            </h2>
          </div>
        </div>
        <hr />
        <div className="row mb-2">
          <div className="col-md-12 text-center mb-4">
            <h3 className="h5">Features<i className="fas fa-list ms-2"></i></h3>
          </div>
        </div>
        <div className="row pt-2">
          <div className="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
            <div className="card nga-card bg-light mb-3">
              <Link to="/bootstrap">
                <div className="card-header">
                  <div className="row">
                    <div className="col-10 col-xl-10">
                      <h4 className="card-title h5">Bootstrap</h4>
                    </div>
                    <div className="col-2 col-xl-2">
                      <i className="fab fa-bootstrap fa-lg text-primary"></i>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <p className="card-text">How to use Buttons, Alerts, Pagination, Tables, Collapses</p>
                </div>
              </Link>
            </div>
          </div>
          <div className="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
            <div className="card nga-card bg-light mb-3">
              <div className="card-header">
                <div className="row">
                  <div className="col-10 col-xl-10">
                    <h4 className="card-title h5">Services</h4>
                  </div>
                  <div className="col-2 col-xl-2">
                    <i className="fas fa-handshake fa-lg text-primary"></i>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">Use services to view a playlist and a youtube player</p>
              </div>
            </div>
          </div>
          <div className="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
            <div className="card nga-card bg-light mb-3">
              <div className="card-header">
                <div className="row">
                  <div className="col-10 col-xl-10">
                    <h4 className="card-title h5">Components</h4>
                  </div>
                  <div className="col-2 col-xl-2">
                    <i className="far fa-clone  fa-lg text-primary"></i>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">Channel component with Input, Output and Event Emitter</p>
              </div>
            </div>
          </div>
          <div className="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
            <div className="card nga-card bg-light mb-3">
              <div className="card-header">
                <div className="row">
                  <div className="col-10 col-xl-10">
                    <h4 className="card-title h5">Reactive Forms</h4>
                  </div>
                  <div className="col-2 col-xl-2">
                    <i className="far fa-file-alt fa-lg text-primary"></i>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">A model-driven approach to handling form inputs</p>
              </div>
            </div>
          </div>
          <div className="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-2">
            <div className="card nga-card bg-light mb-3">
              <div className="card-header">
                <div className="row">
                  <div className="col-10 col-xl-10">
                    <h4 className="card-title h5">Template Driven Forms</h4>
                  </div>
                  <div className="col-2 col-xl-2">
                    <i className="far fa-file-alt fa-lg text-primary"></i>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">Forms are the mainstay of business applications</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

}

export default Home;
